### ISSUE TITLE
Read directly wav files

### ISSUE THREAD

**Issue by jsga** [kahst/BirdNET-Lite#1]
Hi Stefan,

I have a comment about the README file, where you say that:

> You can use any other audio lib if you like, or pass raw audio signals to the model.

On a side note, inspecting the model, it accepts as input an `array([1, 144000], dtype=int32)`. My questions/concerns are:

1. Why do you say you can pass a raw signal directly to the model? Could you elaborate a bit on that?
2. Librosa.load also resamples the signal. When using this model to predict new audio, shouldn't we use the same pre-processing steps you used while training it? In other words, if you used librosa.load with `kaiser_best` resampling method while training, one should use the same while doing inference.

Thanks 👍 
(By the way, great work!)

**Comment by kahst** [comment]
Yes, BirdNET accepts raw audio inputs. Depending on your workflow, you could use the model to process audio from other than files (e.g., streams). As long as your input represents a 3-second chunk of audio that is sampled at 48kHz (hence the input size), you should get a valid prediction. 

Typically, using the exact same pipeline for train and test makes sense. I think in this case, it does not make a huge difference if you resample with any other than 'kaiser_fast'. Although, I never investigated that.

Let me know if you run into any issues when using the repo.

Best,
Stefan

**Comment by jsga** [comment]
Great, thanks for the answer :)

I did some tests, the results are pretty much the same until the 3rd/4th digit.

In a particular example, when loading the audio with 
```python
sig, rate = librosa.load(path, sr=sample_rate, mono=True, res_type="kaiser_fast")
```
I got:
```
{'0.0;3.0': [('Alauda arvensis_Eurasian Skylark', 0.85986483),
             ('Alauda gulgula_Oriental Skylark', 0.14636895),
             ("Gallinago megala_Swinhoe's Snipe", 0.0191465),
             ('Emberiza calandra_Corn Bunting', 0.017170167),
...
```

When I changed that to

```python
from scipy import signal
from scipy.io import wavfile as wav
# (...)
sr, audio =  wav.read(path)
audio48 = signal.resample(audio, np.round((48000/sr) * len(audio)).astype(int))
```
The results could be considered the same:
```
{'0.0;3.0': [('Alauda arvensis_Eurasian Skylark', 0.8598975),
             ('Alauda gulgula_Oriental Skylark', 0.14769696),
             ("Gallinago megala_Swinhoe's Snipe", 0.01915364),
             ('Emberiza calandra_Corn Bunting', 0.017265668),
```
