### ISSUE TITLE
Main Screen showing No detections for today

### ISSUE THREAD

**Issue by lloydbayley** [kahst/BirdNET-Lite#20]
G'day!

A small weirdness, the main screen shows No Detections For Today, yet there are 118 detections right next to it.
There's a conundrum for you! :)

**Comment by DD4WH** [comment]
Check correct time zone in the Settings!

And I think this issue belongs to the BirdNET-Pi repo, not BirdNET-Lite

**Comment by lloydbayley** [comment]
Sorry, my mistake. Was in the wrong place.
